//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreetChat.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class da_DK {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal da_DK() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StreetChat.lang.da-DK", typeof(da_DK).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der er allerede en Admin.
        /// </summary>
        internal static string AdminAlreadyExist {
            get {
                return ResourceManager.GetString("AdminAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der skal være andre i chatten for at du kan blive Admin.
        /// </summary>
        internal static string AloneAdminRequest {
            get {
                return ResourceManager.GetString("AloneAdminRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du er allerede Admin.
        /// </summary>
        internal static string AlreadyAdmin {
            get {
                return ResourceManager.GetString("AlreadyAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made by Stiig &quot;Neophear&quot; Gade - Version {0}.
        /// </summary>
        internal static string BottomText {
            get {
                return ResourceManager.GetString("BottomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopier alt.
        /// </summary>
        internal static string CopyAll {
            get {
                return ResourceManager.GetString("CopyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopier tekst.
        /// </summary>
        internal static string CopyText {
            get {
                return ResourceManager.GetString("CopyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slet alt.
        /// </summary>
        internal static string DelAll {
            get {
                return ResourceManager.GetString("DelAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du skal skrive en besked.
        /// </summary>
        internal static string EmptyMessage {
            get {
                return ResourceManager.GetString("EmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----Admins-----.
        /// </summary>
        internal static string FollowingIsAdmin {
            get {
                return ResourceManager.GetString("FollowingIsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----Hjælp-----
        ///Op/ned for at se tidligere sendte beskeder
        ///CTRL+R for at besvare en privat besked
        ///Du kan højreklikke/dobbeltklikke på brugere
        ///Du kan højreklikke i chatten
        ////admins - Viser alle Admins
        ////afk - Skift status til AFK
        ////info - Lidt info om chatten
        ////ip - Send din egen IP ud i chatten
        ////ips - Se alle brugeres IP
        ////versions - Se hvilken version alle bruger
        ////login password - Log ind som Admin
        ////request - Anmod om Admin hvis ikke der allerede er en
        ////status - Sæt/skift status
        ////username brugerna [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----Info-----
        ///Denne chat blev lavet i Afghanistan på ISAF hold 11 af Stiig Andreas Gade og er sidenhen blevet modificeret
        ///Denne chat er lavet til LAN
        ///Kom gerne med idéer/bugs til stiiggade@gmail.com.
        ///--------------.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} er nu Admin.
        /// </summary>
        internal static string IsNowAdmin {
            get {
                return ResourceManager.GetString("IsNowAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kick.
        /// </summary>
        internal static string Kick {
            get {
                return ResourceManager.GetString("Kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kick %user%.
        /// </summary>
        internal static string KickTT {
            get {
                return ResourceManager.GetString("KickTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du er nu {0}.
        /// </summary>
        internal static string LocalStatusChange {
            get {
                return ResourceManager.GetString("LocalStatusChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du er ikke længere {0}.
        /// </summary>
        internal static string LocalStatusRemoved {
            get {
                return ResourceManager.GetString("LocalStatusRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du.
        /// </summary>
        internal static string LocalUser {
            get {
                return ResourceManager.GetString("LocalUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hedder nu {0}.
        /// </summary>
        internal static string LocalUsernameChange {
            get {
                return ResourceManager.GetString("LocalUsernameChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} loggede af.
        /// </summary>
        internal static string LoggedOff {
            get {
                return ResourceManager.GetString("LoggedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} loggede på.
        /// </summary>
        internal static string LoggedOn {
            get {
                return ResourceManager.GetString("LoggedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeg elsker dig Henriette Strand &lt;3.
        /// </summary>
        internal static string Love {
            get {
                return ResourceManager.GetString("Love", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du skal skrive et brugernavn.
        /// </summary>
        internal static string MissingUsername {
            get {
                return ResourceManager.GetString("MissingUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---Ny version---
        ///Din version er {0}
        ///{1} har version {2}
        ///----------------.
        /// </summary>
        internal static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der er ingen Admin.
        /// </summary>
        internal static string NoAdmin {
            get {
                return ResourceManager.GetString("NoAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyd/statustekst ved ny besked.
        /// </summary>
        internal static string NotifyNewMessage {
            get {
                return ResourceManager.GetString("NotifyNewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kan ikke gøre dette.
        /// </summary>
        internal static string NotPossible {
            get {
                return ResourceManager.GetString("NotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port {0} er allerede i brug. Muligvis fordi du allerede har en chat kørende. Luk den og prøv igen..
        /// </summary>
        internal static string PortInUse {
            get {
                return ResourceManager.GetString("PortInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kan ikke skrive privat til dig selv.
        /// </summary>
        internal static string PrivateToLocalError {
            get {
                return ResourceManager.GetString("PrivateToLocalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se IP.
        /// </summary>
        internal static string SeeIP {
            get {
                return ResourceManager.GetString("SeeIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se %user%&apos;s IP.
        /// </summary>
        internal static string SeeIPTT {
            get {
                return ResourceManager.GetString("SeeIPTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se version.
        /// </summary>
        internal static string SeeVersion {
            get {
                return ResourceManager.GetString("SeeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se %user%&apos;s version.
        /// </summary>
        internal static string SeeVersionTT {
            get {
                return ResourceManager.GetString("SeeVersionTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s IP er {1}.
        /// </summary>
        internal static string ShowIP {
            get {
                return ResourceManager.GetString("ShowIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----IP&apos;er-----.
        /// </summary>
        internal static string ShowIPs {
            get {
                return ResourceManager.GetString("ShowIPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s version er {1}.
        /// </summary>
        internal static string ShowVersion {
            get {
                return ResourceManager.GetString("ShowVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----Versioner-----.
        /// </summary>
        internal static string ShowVersions {
            get {
                return ResourceManager.GetString("ShowVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} er nu {1}.
        /// </summary>
        internal static string StatusChange {
            get {
                return ResourceManager.GetString("StatusChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} er ikke længere {1}.
        /// </summary>
        internal static string StatusRemoved {
            get {
                return ResourceManager.GetString("StatusRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StreetChat.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StreetChat - Ny besked.
        /// </summary>
        internal static string TitleNewMessage {
            get {
                return ResourceManager.GetString("TitleNewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} blev kicket af Admin {1}.
        /// </summary>
        internal static string UserKicked {
            get {
                return ResourceManager.GetString("UserKicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hedder nu {1}.
        /// </summary>
        internal static string UsernameChange {
            get {
                return ResourceManager.GetString("UsernameChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit navn er allerede {0}.
        /// </summary>
        internal static string UsernameExist1 {
            get {
                return ResourceManager.GetString("UsernameExist1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der findes allerede en bruger ved navn {0}.
        /// </summary>
        internal static string UsernameExist2 {
            get {
                return ResourceManager.GetString("UsernameExist2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bruger {0} er ikke online.
        /// </summary>
        internal static string UserNotOnline {
            get {
                return ResourceManager.GetString("UserNotOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----Velkommen-----
        ///Skriv /help eller tryk F1 for at få hjælp til kommandoer
        ///Enjoy :)
        ///-------------------.
        /// </summary>
        internal static string WelcomeString {
            get {
                return ResourceManager.GetString("WelcomeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skriv privat.
        /// </summary>
        internal static string WriteTo {
            get {
                return ResourceManager.GetString("WriteTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skriv privat til %user%.
        /// </summary>
        internal static string WriteToTT {
            get {
                return ResourceManager.GetString("WriteToTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommanden eksisterer ikke. Prøv /help eller F1 for hjælp.
        /// </summary>
        internal static string WrongCommand {
            get {
                return ResourceManager.GetString("WrongCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du blev ikke logget ind som Admin.
        /// </summary>
        internal static string WrongLogin {
            get {
                return ResourceManager.GetString("WrongLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En status må maks være på 5 tegn.
        /// </summary>
        internal static string WrongStatusFormat {
            get {
                return ResourceManager.GetString("WrongStatusFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---Forkert format---
        ///Du må bruge a-z, 0-9, _ og -
        ///Mellem 3 og 20 tegn
        ///--------------------.
        /// </summary>
        internal static string WrongUsernameFormat {
            get {
                return ResourceManager.GetString("WrongUsernameFormat", resourceCulture);
            }
        }
    }
}
