//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreetChat.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_GB {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_GB() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StreetChat.lang.en-GB", typeof(en_GB).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There already is an Admin.
        /// </summary>
        internal static string AdminAlreadyExist {
            get {
                return ResourceManager.GetString("AdminAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There have to be more than you in the chat to make you Admin.
        /// </summary>
        internal static string AloneAdminRequest {
            get {
                return ResourceManager.GetString("AloneAdminRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already Admin.
        /// </summary>
        internal static string AlreadyAdmin {
            get {
                return ResourceManager.GetString("AlreadyAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made by Stiig &quot;Neophear&quot; Gade - Version {0}.
        /// </summary>
        internal static string BottomText {
            get {
                return ResourceManager.GetString("BottomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy all.
        /// </summary>
        internal static string CopyAll {
            get {
                return ResourceManager.GetString("CopyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy text.
        /// </summary>
        internal static string CopyText {
            get {
                return ResourceManager.GetString("CopyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all text.
        /// </summary>
        internal static string DelAll {
            get {
                return ResourceManager.GetString("DelAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to write a message.
        /// </summary>
        internal static string EmptyMessage {
            get {
                return ResourceManager.GetString("EmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----Admins-----.
        /// </summary>
        internal static string FollowingIsAdmin {
            get {
                return ResourceManager.GetString("FollowingIsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----Help-----
        ///Up/down to see previous messages
        ///CTRL+R to reply a private message
        ///You can right- and doubleclick on users
        ///You can rightclick in the chat
        ////admins - Shows all Admins
        ////afk - Set status to AFK
        ////info - Some info about the chat
        ////ip - Broadcast your own IP
        ////ips - Show all users IP
        ////versions - See all users versions
        ////login password - Log in as Admin
        ////request - Request to become Admin if there aren&apos;t any
        ////status - Set/change your status
        ////username username - Change username
        ////w username  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----Info-----
        ///This chat was made in Afghanistan on ISAF 11 by Stiig Andreas Gade and have since then been modified
        ///This chat is made for LAN only
        ///Feel free to come with bugs/suggestions to stiiggade@gmail.com
        ///--------------.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is now Admin.
        /// </summary>
        internal static string IsNowAdmin {
            get {
                return ResourceManager.GetString("IsNowAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kick.
        /// </summary>
        internal static string Kick {
            get {
                return ResourceManager.GetString("Kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kick %user%.
        /// </summary>
        internal static string KickTT {
            get {
                return ResourceManager.GetString("KickTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now {0}.
        /// </summary>
        internal static string LocalStatusChange {
            get {
                return ResourceManager.GetString("LocalStatusChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are no longer {0}.
        /// </summary>
        internal static string LocalStatusRemoved {
            get {
                return ResourceManager.GetString("LocalStatusRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name is now {0}.
        /// </summary>
        internal static string LocalUsernameChange {
            get {
                return ResourceManager.GetString("LocalUsernameChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} logged off.
        /// </summary>
        internal static string LoggedOff {
            get {
                return ResourceManager.GetString("LoggedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} logged on.
        /// </summary>
        internal static string LoggedOn {
            get {
                return ResourceManager.GetString("LoggedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I love you Henriette Strand &lt;3.
        /// </summary>
        internal static string Love {
            get {
                return ResourceManager.GetString("Love", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to write a username.
        /// </summary>
        internal static string MissingUsername {
            get {
                return ResourceManager.GetString("MissingUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---New version---
        ///Your version is {0}
        ///{1} has version {2}
        ///----------------.
        /// </summary>
        internal static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no Admins.
        /// </summary>
        internal static string NoAdmin {
            get {
                return ResourceManager.GetString("NoAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound/statustext at new message.
        /// </summary>
        internal static string NotifyNewMessage {
            get {
                return ResourceManager.GetString("NotifyNewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t do that.
        /// </summary>
        internal static string NotPossible {
            get {
                return ResourceManager.GetString("NotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port {0} is already in use. Probably because you have a chat running already. Close it and try again..
        /// </summary>
        internal static string PortInUse {
            get {
                return ResourceManager.GetString("PortInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t send private to yourself.
        /// </summary>
        internal static string PrivateToLocalError {
            get {
                return ResourceManager.GetString("PrivateToLocalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See IP.
        /// </summary>
        internal static string SeeIP {
            get {
                return ResourceManager.GetString("SeeIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See %user%&apos;s IP.
        /// </summary>
        internal static string SeeIPTT {
            get {
                return ResourceManager.GetString("SeeIPTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See version.
        /// </summary>
        internal static string SeeVersion {
            get {
                return ResourceManager.GetString("SeeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See %user%&apos;s version.
        /// </summary>
        internal static string SeeVersionTT {
            get {
                return ResourceManager.GetString("SeeVersionTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s IP is {1}.
        /// </summary>
        internal static string ShowIP {
            get {
                return ResourceManager.GetString("ShowIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----IP&apos;s-----.
        /// </summary>
        internal static string ShowIPs {
            get {
                return ResourceManager.GetString("ShowIPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s version is {1}.
        /// </summary>
        internal static string ShowVersion {
            get {
                return ResourceManager.GetString("ShowVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----Versions-----.
        /// </summary>
        internal static string ShowVersions {
            get {
                return ResourceManager.GetString("ShowVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is now {1}.
        /// </summary>
        internal static string StatusChange {
            get {
                return ResourceManager.GetString("StatusChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is no longer {1}.
        /// </summary>
        internal static string StatusRemoved {
            get {
                return ResourceManager.GetString("StatusRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StreetChat.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StreetChat - New message.
        /// </summary>
        internal static string TitleNewMessage {
            get {
                return ResourceManager.GetString("TitleNewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} got kicked by Admin {1}.
        /// </summary>
        internal static string UserKicked {
            get {
                return ResourceManager.GetString("UserKicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} changed name to {1}.
        /// </summary>
        internal static string UsernameChange {
            get {
                return ResourceManager.GetString("UsernameChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name is already {0}.
        /// </summary>
        internal static string UsernameExist1 {
            get {
                return ResourceManager.GetString("UsernameExist1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user named {0} already exist.
        /// </summary>
        internal static string UsernameExist2 {
            get {
                return ResourceManager.GetString("UsernameExist2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user named {0} online.
        /// </summary>
        internal static string UserNotOnline {
            get {
                return ResourceManager.GetString("UserNotOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----Welcome-----
        ///Write /help or press F1 to get help to commands
        ///Enjoy :)
        ///-------------------.
        /// </summary>
        internal static string WelcomeString {
            get {
                return ResourceManager.GetString("WelcomeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send private message.
        /// </summary>
        internal static string WriteTo {
            get {
                return ResourceManager.GetString("WriteTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send private message to %user%.
        /// </summary>
        internal static string WriteToTT {
            get {
                return ResourceManager.GetString("WriteToTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That command does not exist. Write /help or press F1 to see available commands.
        /// </summary>
        internal static string WrongCommand {
            get {
                return ResourceManager.GetString("WrongCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You weren&apos;t logged in as Admin.
        /// </summary>
        internal static string WrongLogin {
            get {
                return ResourceManager.GetString("WrongLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A status can&apos;t be more than 5 characters.
        /// </summary>
        internal static string WrongStatusFormat {
            get {
                return ResourceManager.GetString("WrongStatusFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---Wrong format---
        ///You can use a-z, 0-9, _ and -
        ///Between 3 and 20 characters
        ///--------------------.
        /// </summary>
        internal static string WrongUsernameFormat {
            get {
                return ResourceManager.GetString("WrongUsernameFormat", resourceCulture);
            }
        }
    }
}
